language: node_js
node_js:
  - 8.15
  - 10

services:
  - mongodb

cache: npm
script: npm test

# Don’t build pushes to branches other than our published branches. (This doesn’t affect PR
# builds, which are separate from branch builds in Travis. If we didn’t have this config,
# Travis would run both types of builds for PRs, consuming our concurrent builds.)
branches:
  only:
    - master
