language: node_js
node_js:
  - 8.15
  - 10

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - "npm i coveralls nyc"
  - "sleep 15"
script: "npm run eslint;npx nyc ava"
after_script: "npm run report"

branches:
  only:
    - master
